// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.pruebaseguridad.model;

import ar.edu.um.pruebaseguridad.model.UserRoleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserRoleDataOnDemand_Roo_Configurable {
    
    declare @type: UserRoleDataOnDemand: @Configurable;
    
}
